-- ===== ORGANIZATIONS (Tổ chức) =====
CREATE TABLE IF NOT EXISTS organizations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);

-- ===== ROLES (Định nghĩa 11 Role & Phân cấp) =====
CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_key VARCHAR(50) NOT NULL UNIQUE,
    role_name VARCHAR(100) NOT NULL,
    role_level INTEGER NOT NULL,
    description TEXT
);

-- Seeding 11 Roles
INSERT INTO roles (role_key, role_name, role_level, description)
VALUES
('bod', 'Ban Điều Hành', 1, 'Quyền cao nhất, giám sát tổng thể.'),
('admin', 'Quản trị viên Hệ thống', 2, 'Quản lý backend, cấu hình, xử lý tranh chấp.'),
('leader', 'Trưởng nhóm/Dự án', 3, 'Quản lý team trực tiếp, phê duyệt vận hành.'),
('mentor_coach', 'Giảng viên/Chuyên gia', 4, 'Tham gia mentoring và chấm điểm phản biện.'),
('student_l3', 'Sinh viên Level 3', 5, 'Thực chiến, có quyền giao task phụ và chấm điểm sơ bộ.'),
('student_l2', 'Sinh viên Level 2', 6, 'Thực thi, cập nhật trạng thái tasks.'),
('student_l1', 'Sinh viên Level 1', 7, 'Cấp độ làm quen, quyền hạn cơ bản.'),
('employee', 'Nhân sự Dự án', 8, 'Nhân sự chính thức, quyền hạn tiêu chuẩn.'),
('collaborator', 'Cộng tác viên', 8, 'CTV theo dự án/thời vụ.'),
('customer_stakeholder', 'Khách hàng/Cổ đông', 9, 'Đối tượng bên ngoài, chỉ xem báo cáo công khai/CRM.'),
('pending_approval', 'Chờ Phê Duyệt', 99, 'Tài khoản mới, không có quyền truy cập ứng dụng chính.')
ON CONFLICT (role_key) DO NOTHING;

-- ===== USER PROFILES (Hồ sơ & Trạng thái Phê duyệt) =====
-- Tạo kiểu dữ liệu ENUM cho trạng thái tài khoản
CREATE TYPE account_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

CREATE TABLE IF NOT EXISTS user_profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, -- Khóa liên kết Auth
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    manager_id UUID REFERENCES user_profiles(id),
    org_id UUID REFERENCES organizations(id) ON DELETE CASCADE,
    account_status account_status DEFAULT 'PENDING' NOT NULL, -- Workflow Phê duyệt
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- ===== MEMBERSHIPS (Liên kết User với Role và Team) =====
CREATE TABLE IF NOT EXISTS memberships (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    org_id UUID REFERENCES organizations(id) ON DELETE CASCADE,
    role_id BIGINT REFERENCES roles(id) ON DELETE RESTRICT,
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(user_id, org_id)
);

-- ===== PROJECTS (Dự án & Tọa độ Geolocation) =====
CREATE TABLE IF NOT EXISTS projects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_name VARCHAR(255) NOT NULL UNIQUE,
    project_code VARCHAR(50) UNIQUE,
    leader_user_id UUID REFERENCES user_profiles(id) ON DELETE SET NULL,
    
    -- Geolocation Fields
    allowed_latitude NUMERIC(10, 8),   
    allowed_longitude NUMERIC(11, 8),  
    allowed_radius_meters INTEGER DEFAULT 50,
    created_at TIMESTAMP DEFAULT NOW()
);
-- ===== ATTENDANCE LOGS (Chấm công & Tọa độ thực tế) =====
CREATE TABLE IF NOT EXISTS attendance_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    project_id UUID REFERENCES projects(id) ON DELETE SET NULL,
    check_in_time TIMESTAMP,
    check_out_time TIMESTAMP,
    total_hours NUMERIC(5, 2), -- Được tính tự động
    
    -- Geolocation Tracking
    check_in_lat FLOAT,
    check_in_lon FLOAT,
    is_location_valid BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW()
);

-- ===== TASKS (Công việc) =====
CREATE TYPE task_priority AS ENUM ('low', 'medium', 'high', 'urgent');
CREATE TYPE task_status AS ENUM ('todo', 'in_progress', 'done', 'blocked');
CREATE TABLE IF NOT EXISTS tasks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(255) NOT NULL,
    status task_status DEFAULT 'todo',
    priority task_priority DEFAULT 'medium',
    assignee_id UUID REFERENCES user_profiles(id) ON DELETE SET NULL,
    assigned_by UUID NOT NULL REFERENCES user_profiles(id),
    due_date DATE,
    created_at TIMESTAMP DEFAULT NOW()
);

-- ===== EVALUATIONS (Đánh giá ASK) =====
CREATE TABLE IF NOT EXISTS evaluations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    evaluator_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    evaluatee_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    evaluation_date DATE NOT NULL,
    technical_skills INT,
    attitude INT,
    knowledge INT,
    is_approved BOOLEAN DEFAULT FALSE, -- Phê duyệt bởi BOD/Admin
    created_at TIMESTAMP DEFAULT NOW()
);

-- ===== SALARIES (Lương thưởng) =====
CREATE TABLE IF NOT EXISTS salaries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    base_salary DECIMAL(12, 2) NOT NULL,
    bonus DECIMAL(12, 2),
    created_at TIMESTAMP DEFAULT NOW()
);

-- ===== LEAVE REQUESTS (Nghỉ phép) =====
CREATE TYPE leave_type AS ENUM ('sick', 'annual', 'personal', 'unpaid', 'other');
CREATE TYPE leave_request_status AS ENUM ('pending', 'approved', 'rejected');
CREATE TABLE IF NOT EXISTS leave_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    type leave_type NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason TEXT NOT NULL,
    status leave_request_status DEFAULT 'pending',
    approved_by UUID REFERENCES user_profiles(id),
    created_at TIMESTAMP DEFAULT NOW()
);
-- A. Hàm và Trigger Tự động tạo Profile PENDING (Manual Vetting Workflow)
CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS TRIGGER AS $$
DECLARE
    pending_role_id BIGINT;
BEGIN
    SELECT id INTO pending_role_id FROM public.roles WHERE role_key = 'pending_approval';

    -- 1. Insert vào bảng user_profiles
    INSERT INTO public.user_profiles (id, email, name, account_status)
    VALUES (
        NEW.id,
        NEW.email,
        NEW.raw_user_meta_data ->> 'name',
        'PENDING' 
    );
    
    -- 2. Insert vào bảng memberships với Role PENDING
    INSERT INTO public.memberships (user_id, role_id)
    VALUES (
        NEW.id,
        pending_role_id
    );

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();


-- B. Hàm và Trigger Tự động tính Total Hours (Attendance)
CREATE OR REPLACE FUNCTION public.calculate_total_hours_log()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.check_in_time IS NOT NULL AND NEW.check_out_time IS NOT NULL THEN
        NEW.total_hours = ROUND(
            EXTRACT(EPOCH FROM (NEW.check_out_time - NEW.check_in_time)) / 3600,
            2
        );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER attendance_calc_trigger
BEFORE INSERT OR UPDATE OF check_in_time, check_out_time ON public.attendance_logs
FOR EACH ROW EXECUTE FUNCTION public.calculate_total_hours_log();
-- KÍCH HOẠT RLS (BẮT BUỘC)
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE evaluations ENABLE ROW LEVEL SECURITY;
ALTER TABLE salaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE leave_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;


-- POLICIES CỐT LÕI

-- USER PROFILES
CREATE POLICY "user_profiles_view_self" ON user_profiles FOR SELECT USING (id = auth.uid());
CREATE POLICY "user_profiles_view_team" ON user_profiles FOR SELECT USING (manager_id = auth.uid());
CREATE POLICY "user_profiles_update_self" ON user_profiles FOR UPDATE USING (id = auth.uid());


-- ATTENDANCE (LEADER/TEAM)
CREATE POLICY "attendance_manage_self" ON attendance_logs FOR ALL USING (user_id = auth.uid());
CREATE POLICY "attendance_view_team" ON attendance_logs FOR SELECT USING (
    user_id IN (SELECT id FROM user_profiles WHERE manager_id = auth.uid())
);


-- LEAVE REQUESTS (LEADER/TEAM)
CREATE POLICY "leaves_manage_self" ON leave_requests FOR ALL USING (user_id = auth.uid());
CREATE POLICY "leaves_manage_team" ON leave_requests FOR ALL USING (
    user_id IN (SELECT id FROM user_profiles WHERE manager_id = auth.uid())
);

-- SALARIES (CHỈ ADMIN/BOD)
CREATE POLICY "salaries_restrict_access" ON salaries FOR ALL USING (
    EXISTS (
        SELECT 1 FROM memberships AS m JOIN roles AS r ON m.role_id = r.id
        WHERE m.user_id = auth.uid() AND r.role_key IN ('admin', 'bod')
    )
);

-- TASKS (ASSIGNED)
CREATE POLICY "tasks_view_assigned" ON tasks FOR ALL USING (assignee_id = auth.uid() OR assigned_by = auth.uid());